//
// Created by omer on 19/12/2019.
//

#ifndef ALGORITHMICPROGRAMMINGPROJECT__COMMAND_H_
#define ALGORITHMICPROGRAMMINGPROJECT__COMMAND_H_

class Command {
 public:
  int execute();
};

#endif //ALGORITHMICPROGRAMMINGPROJECT__COMMAND_H_
